use log::debug;

pub use crate::db::schema::Allocation;

impl Allocation {
    pub async fn insert(
        pool: &sqlx::sqlite::SqlitePool,
        alloc: Allocation,
    ) -> Result<(), sqlx::Error> {
        let row = sqlx::query_as!(
            Allocation,
            "INSERT INTO allocations (
                origin_datetime,
                origin_location,
                origin_country_code_iso,
                origin_subsidiary_information_code,
                origin_subsidiary_information_company,
                date,
                dest_location,
                dest_country_code_iso,
                dest_subsidiary_information_code,
                dest_subsidiary_information_company,
                dest_datetime,
                allocation_origin_datetime,
                allocation_origin_location,
                allocation_origin_country_code_iso,
                allocation_origin_subsidiary_information_code,
                allocation_origin_subsidiary_information_company,
                allocation_dest_datetime,
                allocation_dest_location,
                allocation_dest_country_code_iso,
                allocation_dest_subsidiary_information_code,
                allocation_dest_subsidiary_information_company,
                resource_group_id,
                sequence_number,
                resource_group_position,
                diagram_no,
                origin_miles,
                destination_miles,
                reversed
            ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, ?20, ?21, ?22, ?23, ?24, ?25, ?26, ?27, ?28)
            RETURNING
                id,
                origin_datetime,
                origin_location,
                origin_country_code_iso,
                origin_subsidiary_information_code,
                origin_subsidiary_information_company,
                date,
                dest_location,
                dest_country_code_iso,
                dest_subsidiary_information_code,
                dest_subsidiary_information_company,
                dest_datetime,
                allocation_origin_datetime,
                allocation_origin_location,
                allocation_origin_country_code_iso,
                allocation_origin_subsidiary_information_code,
                allocation_origin_subsidiary_information_company,
                allocation_dest_datetime,
                allocation_dest_location,
                allocation_dest_country_code_iso,
                allocation_dest_subsidiary_information_code,
                allocation_dest_subsidiary_information_company,
                resource_group_id,
                sequence_number,
                resource_group_position,
                diagram_no,
                origin_miles,
                destination_miles,
                reversed",
                alloc.origin_datetime,
                alloc.origin_location,
                alloc.origin_country_code_iso,
                alloc.origin_subsidiary_information_code,
                alloc.origin_subsidiary_information_company,
                alloc.date,
                alloc.dest_location,
                alloc.dest_country_code_iso,
                alloc.dest_subsidiary_information_code,
                alloc.dest_subsidiary_information_company,
                alloc.dest_datetime,
                alloc.allocation_origin_datetime,
                alloc.allocation_origin_location,
                alloc.allocation_origin_country_code_iso,
                alloc.allocation_origin_subsidiary_information_code,
                alloc.allocation_origin_subsidiary_information_company,
                alloc.allocation_dest_datetime,
                alloc.allocation_dest_location,
                alloc.allocation_dest_country_code_iso,
                alloc.allocation_dest_subsidiary_information_code,
                alloc.allocation_dest_subsidiary_information_company,
                alloc.resource_group_id,
                alloc.sequence_number,
                alloc.resource_group_position,
                alloc.diagram_no,
                alloc.origin_miles,
                alloc.destination_miles,
                alloc.reversed
        )
        .fetch_one(pool)
        .await?;
        debug!("Inserted Allocation with ID: {:?}", row.id);
        Ok(())
    }
}
