
name: CI

jobs:
    build:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        permissions:
          contents: read
          issues: write
        steps:
            - uses: actions/checkout@v2
            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: devramsean0
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build Docker image
              run: docker build -t ghcr.io/devramsean0/trainallocationviewer:web-latest
            - name: Push Docker image
              run: docker push ghcr.io/devramsean0/trainallocationviewer:web-latest